version: '2'

services:

  nginx:
    build:
      context: .docker
      dockerfile: nginx.dockerfile
    links:
      - node1:node1
      - node2:node2
      - node3:node3
    depends_on:
      - node1
      - node2
      - node3
    ports:
      - "8080:80"
    networks:
      - app-network

  node1:
    build:
      context: .docker
      dockerfile: node.dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node1
    networks:
      - app-network
      - db-network

  node2:
    build:
      context: .docker
      dockerfile: node.dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node2
    networks:
      - app-network
      - db-network

  node3:
    build:
      context: .docker
      dockerfile: node.dockerfile
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "3000"
    environment:
      - INSTANCE=node3
    networks:
      - app-network
      - db-network

  couchdb:
    build:
      context: .docker
      dockerfile: couchdb.dockerfile
    working_dir: /usr/src/db
    volumes:
      - ./couchdb:/usr/src/db
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin
    networks:
      - db-network
networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge
