services:
    nginx:
        image: nginx:1.21.6
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
            - ./static:/var/www/html/static
            - ./certs:/etc/nginx/certs
        depends_on:
            - node1
            - node2
            - node3
        ports:
            - "8888:80"
            - "443:443"
        restart: always
        networks:
            - app-network

    node1:
        build:
            context: app
            dockerfile: Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./app:/usr/src/app/
        ports:
            - "3000"
        environment:
            - INSTANCE=node1
            - DB_NAME=mongodb
            - PORT=3000
        networks:
            - app-network
            - db-network

    node2:
        build:
            context: app
            dockerfile: Dockerfile
        working_dir: /usr/src/app
        volumes:
            - ./app:/usr/src/app/
        ports:
            - "3000"
        environment:
            - INSTANCE=node2
            - DB_NAME=mongodb
            - PORT=3000
        networks:
            - app-network
            - db-network

    # node3:
    #     build:
    #         context: app
    #         dockerfile: Dockerfile
    #     working_dir: /usr/src/app
    #     volumes:
    #         - ./app:/usr/src/app/
    #     ports:
    #         - "3000"
    #     environment:
    #         - INSTANCE=node3
    #         - DB_NAME=mongodb
    #         - PORT=3000
    #     networks:
    #         - app-network
    #         - db-network

    mongodb:
        image: mongo:focal
        working_dir: /usr/src/db
        ports:
            - "27017:27017"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=admin
            - MONGO_INITDB_ROOT_PASSWORD=admin
        networks:
            - db-network
        command: mongod --quiet --logpath /dev/null

networks:
    app-network:
        driver: bridge
    db-network:
        driver: bridge
