name: Test-nodeJS

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest # tira su una VM ubuntu per fare i test

    strategy:
      matrix:
        node-version: [18.x] #versione di NodeJs

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }} 
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
      working-directory: ./app
    - run: npm test
      working-directory: ./app
